image: Visual Studio 2017
branches:
  only:
  - master
build_script:
- cmd: C:\projects\appveyor-playground\build.bat
test: off
artifacts:
- path: readme.md
  name: README
deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: jSFkl4pbQUbrR2Yqh8MEAUmJ8uP6/Pm6sca+pd6HYB04B/zi4Y92WF0FG6d1/PdF
  artifact: README
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
