image: Visual Studio 2017
branches:
  only:
  - master
install:
- ps: C:\projects\appveyor-playground\set-version.ps1
build_script:
- cmd: C:\projects\appveyor-playground\build.bat
test: off
artifacts:
- path: \AppVeyorPlayground\bin\Release\netcoreapp1.1\AppVeyorPlayground.dll
  name: dll
deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: jSFkl4pbQUbrR2Yqh8MEAUmJ8uP6/Pm6sca+pd6HYB04B/zi4Y92WF0FG6d1/PdF
  artifact: dll
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '$(ScmBackupVersion)'
  assembly_file_version: '$(ScmBackupVersion)'
  assembly_informational_version: '$(ScmBackupVersion)-$(APPVEYOR_REPO_COMMIT)'
